server:
  port: 8080

spring:
  datasource:
    test1:
      jdbc-url: jdbc:mysql://10.0.10.118:3306/test1?Unicode=true&characterEncoding=UTF-8&useSSL=true
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: 123456

    test2:
      jdbc-url: jdbc:mysql://10.0.10.118:3306/test2?Unicode=true&characterEncoding=UTF-8&useSSL=true
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: 123456
