server:
  port: 8080

spring:
  datasource:
    test1:
      type: com.alibaba.druid.pool.DruidDataSource
      url: jdbc:mysql://10.0.10.118:3306/test1?Unicode=true&characterEncoding=UTF-8&useSSL=true
      username: root
      password: 123456
      name: test1
        # 监控统计拦截的filters 有stat,wall,log4j
      filters: stat


    test2:
      type: com.alibaba.druid.pool.DruidDataSource
      url: jdbc:mysql://10.0.10.118:3306/test2?Unicode=true&characterEncoding=UTF-8&useSSL=true
      username: root
      password: 123456
      name: test2
        # 监控统计拦截的filters 有stat,wall,log4j
      filters: stat